# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
#â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
---
# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # - {trigger: '->', replace: â†’, word: true} # unicode arrow
  # - {trigger: ' mm', replace: ' ğŸ™ˆ'}

  - trigger: '::date'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%m/%d/%Y'

  - trigger: '::isodate'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%Y-%m-%d'

  - trigger: '::time'
    replace: '{{time}}'
    vars:
      - name: time
        type: date
        params:
          format: '%X'

  - trigger: ':flip:'
    replace: '(ãƒÂ°Ğ”Â°ï¼‰ãƒï¸µ â”»â”â”»'

  - trigger: ':shrug:'
    replace: "Â¯\\_(ãƒ„)_/Â¯"

  - trigger: '::ip'
    replace: '{{ip}}'
    vars:
      - name: ip
        type: shell
        params:
          cmd: 'curl ifconfig.me'

  - {trigger: '<3', replace: 'ğŸ©¶'} # use grey haeart instead of red one
  - trigger: ':wave:'
    replace: ğŸ‘‹
    word: true
  - trigger: ':heart:'
    replace: â¤ï¸
    word: true
  - trigger: ':thumb:'
    replace: ğŸ‘
    word: true
  - trigger: ':+1:'
    replace: ğŸ‘
    word: true
  - trigger: ':thumbsup:'
    replace: ğŸ‘
    word: true
  - trigger: ':-1:'
    replace: ğŸ‘
    word: true
  - trigger: ':thumbsdown:'
    replace: ğŸ‘
    word: true
  - trigger: ':flex:'
    replace: ğŸ’ª
    word: true
  - trigger: ':pray:'
    replace: ğŸ™
    word: true
  - trigger: ':rock:'
    replace: ğŸ¤˜
    word: true
  - trigger: ':rofl:'
    replace: ğŸ¤£
    word: true
  - trigger: ':poop:'
    replace: ğŸ’©
    word: true
  - trigger: ':100:'
    replace: ğŸ’¯
    word: true
  - trigger: ':eyes:'
    replace: ğŸ‘€
    word: true
  - trigger: ':facepalm:'
    replace: ğŸ¤¦
    word: true
  - trigger: ':hands:'
    replace: ğŸ™ŒğŸ¼
    word: true
